services:
  - type: web
    name: mapa-argentina-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PB_DATA
        value: /pb/pb_data
      - key: PB_ENCRYPTION_KEY
        generateValue: true
    disk:
      name: pocketbase-data
      mountPath: /pb/pb_data
      sizeGB: 1
